### ISSUE TITLE
XSS in 404.php and header.php

### ISSUE THREAD

**Issue by honoki** [molovo/bushwick#4]
The file `/bushwick-master/404.php` is prone to XSS-attacks in:

```
 <p>Unfortunately, the page <code>/<?php echo current_url(); ?></code> could not be found.
```

The function call `current_url()` should be replaced by `htmlentities(current_url())`.

The same function is called in `header.php` and possibly other places.

**Comment by honoki** [comment]
This appears to be an error in the default theme as well. I'm gonna publish an issue there too.

**Comment by WillPresley** [comment]
Just popping in to:
1. Confirm the XSS vulnerability.
2. Confirm that honoki's method of passing the url through the htmlentities function works well.

**Comment by molovo** [comment]
Haven't touched anchor in awhile, so no idea if this theme still even works. If it does and someone wants to submit a PR for this fix I'll happily merge.
